<?
$admin_menu = array(
    '-'=>'Главное',
    'user,logout'=>'Выйти',
    '--'=>'Статистика, отчеты',
    'send,demand'=>'Статистика отправлений',
    'send,saveFree'=>'Статистика сохранений',
    'pj_state,stat'=>'Общая статистика',
    'state,stateTmpl'=>'Отчет по шаблонам',
    'state,templates'=>'Отчете по шаблонам 2',
    'state,ok_errors'=>'OK Ошибки',  
    '---'=>'Документы',
    'sys,tasks'=>'Задачи',
    'utils,faq'=>'Типичные вопросы',
    'utils,manage'=>'Управление', 
    '----'=>'Система',
    'sys,sysInfo'=>'Система',
    'utils,nginx_stat'=>'Статистика NGINX',
    'utils,of_js_errors'=>'Статистика JS ошибок',
    'utils,of_pjok_errors'=>'PJOK ошибки', 
    '-----'=>'Праздники',   
    'holiday,getList'=>'Праздники', 
    'holiday,manageHolidayTmpls'=>'Управление шаблонами', 
    'holiday,getNames'=>'Имена', 
    'holiday,getNameHolidays'=>'Именины',
    '--------'=>'SEO', 
    'seo,texts'=>'Тексты', 
    'seo,words'=>'Запросы-ключевые слова', 
    'seo,sitemap'=>'Sitemap генератор', 
    '---------'=>'Быстрые ссылки',
    'quickLinks,view'=>'Список ссылок',
    'quickLinks,blocks'=>'Блоки ссылок', 
    '----------'=>'Каталог',
    'catalog,groups'=>'Разделы',
    'catalog,tmpls'=>'Групповое управление',
    'catalog,edit'=>'Параметры шаблона',
    'catalog,add'=>'Добавить шаблон',  
    '-----------'=>'Транзакции',         
    'transaction,tlist'=>'Список операций',         
    'transaction,add'=>'Добавить операцию',
);

$default_task = array('utils', 'faq');
?>