<?
$refs = array('context'=>array(
    'direct',
	'catalog',
	'banner',
	'banner_text',
	'banner_img',
	'friend_invitation',
	'friend_feed',
	'friend_notification',
	'present',
	'present_tooltip',
	'common_apps',
	'user_apps',
	'friend_apps',
	'recommended_apps',
	'new_apps',
	'top_apps',
	'pay_attention_apps',
	'app_search_apps',
	'shops_catalog_apps',
	'our_apps',
	'short_apps'
));
?>